version: '3.8'

services:
  
  aspnetcore:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - beautysalon-postgres
    ports:
      - "80:80"
    networks:
      - net
  
  beautysalon-postgres:
    container_name: beautysalon-postgres
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5432"
    volumes:
      - beautysalon-postgres-volume:/var/lib/postgresql/data
    networks:
      - net

volumes:
  beautysalon-postgres-volume:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24