version: '3.8'

services:
  
  beautysalon-postgres:
    container_name: beautysalon-postgres
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5433"
    volumes:
      - beautysalon-postgres-volume:/var/lib/postgresql/data

volumes:
  beautysalon-postgres-volume: